// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHXiRJ7CaAvXD2XJVewkNFUuw5KcfjbCs',
    appId: '1:289479140720:web:5f89c1ec98d0e7dd725bb5',
    messagingSenderId: '289479140720',
    projectId: 'class-room-8dddb',
    authDomain: 'class-room-8dddb.firebaseapp.com',
    storageBucket: 'class-room-8dddb.appspot.com',
    measurementId: 'G-N0VB2FV9R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBazBhfvd9kCWHPDJX1q3An_05TPWtqI-o',
    appId: '1:289479140720:android:c8ea1044293af76e725bb5',
    messagingSenderId: '289479140720',
    projectId: 'class-room-8dddb',
    storageBucket: 'class-room-8dddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_cQBe-NtiQuJybUyzn3FcQZ_HWiOUjD4',
    appId: '1:289479140720:ios:9bd3aac3e82fe14c725bb5',
    messagingSenderId: '289479140720',
    projectId: 'class-room-8dddb',
    storageBucket: 'class-room-8dddb.appspot.com',
    iosClientId: '289479140720-8rieteahg1m31p7hpar562p1pgpf8tns.apps.googleusercontent.com',
    iosBundleId: 'com.anhkiet.classroom.classRoomChin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_cQBe-NtiQuJybUyzn3FcQZ_HWiOUjD4',
    appId: '1:289479140720:ios:9bd3aac3e82fe14c725bb5',
    messagingSenderId: '289479140720',
    projectId: 'class-room-8dddb',
    storageBucket: 'class-room-8dddb.appspot.com',
    iosClientId: '289479140720-8rieteahg1m31p7hpar562p1pgpf8tns.apps.googleusercontent.com',
    iosBundleId: 'com.anhkiet.classroom.classRoomChin',
  );
}
